# -- Server Port
server:
  port: 8787

# -- Eureka
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8787/eureka
    register-with-eureka: false
    fetch-registry: false

# -- Default spring configuration
spring:
  application:
    name: PoHab